spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mess_management_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&serverTimezone=UTC}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Khushi@123}
  jpa:
    database-platform: ${SPRING_JPA_DIALECT:org.hibernate.dialect.MySQLDialect}
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
